### ISSUE TITLE
LOGS_CHANNEL error 400

### ISSUE THREAD

**Issue by EDM115** [Itz-fork/Unzipper-Bot#13]
I have a little problem of… comprehension 😅 regarding to `LOGS_CHANNEL`  
  
I tried to deploy, and then heroku logs says :  
`Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")`  

So what value do we need to put as LOGS_CHANNEL ?  
Channel id (like `-100160010XXXX`) ?  
Channel name (like `@randomchannel`) ?  
  
I'm lost 😭

**Comment by Itz-fork** [comment]
LOGS_CHANNEL = YOUR_CHANNEL _ID (Ex: `-10012334455`)
