### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by sholoomail** [Itz-fork/Unzipper-Bot#15]
Hi.
When i deploy this repo to heroku this message appear:

We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by EDM115** [comment]
Fork it, then try to deploy again (also change the URL in readme with your repo url)

**Comment by sholoomail** [comment]
> Fork it, then try to deploy again (also change the URL in readme with your repo url)

Thanks brother. It works properly.
