### ISSUE TITLE
Bot not responding 

### ISSUE THREAD

**Issue by DarkAnonymousGuy** [Itz-fork/Unzipper-Bot#16]
After successfully deployed the bot is not responding

**Comment by Itz-fork** [comment]
**If** the deployment was **successful** your bot should respond. Try redeploying

**Comment by Itz-fork** [comment]
Can you send logs? because I'm pretty sure this isn't a bug as the [@NexaUnzipper_bot](https://t.me/NexaUnzipper_bot) is also running on this repo (arch branch).
